title: Gautam Ottur
description: Personal website of Gautam Ottur.
theme: just-the-docs

url: https://ottur.info

aux_links:
  Template Repository: https://github.com/gautamottur/gautamottur.github.io
